import { useEffect, useMemo, useRef, useState } from 'react';
import { ArrowDown, ArrowLeft, ArrowUp, CalendarDays, ChevronRight, Edit3, Eye, Loader2, Plus, Save, Search, Settings2, SkipForward, Trash2, X } from 'lucide-react';
import { videosApi } from '../../lib/api';
import { useNavigate } from 'react-router-dom';

const ytId = (url='') => { const m=url.match(/(?:youtu\.be\/|youtube\.com\/(?:watch\?v=|embed\/|shorts\/))([\w-]{11})/); return m?.[1] || ''; };
const fmt = s => `${String(Math.floor(Number(s||0)/60)).padStart(2,'0')}:${String(Math.floor(Number(s||0)%60)).padStart(2,'0')}`;
const emptyQ=()=>({time:0,question:'',explanation:'',options:['','','',''],correctAnswer:0});

export default function VideosPage(){
 const navigate=useNavigate();
 const [offerings,setOfferings]=useState([]),[selectedOffering,setSelectedOffering]=useState(''),[videos,setVideos]=useState([]),[loading,setLoading]=useState(true),[search,setSearch]=useState(''),[message,setMessage]=useState(null),[videoModal,setVideoModal]=useState(null),[editor,setEditor]=useState(null),[editorTab,setEditorTab]=useState('questions'),[qModal,setQModal]=useState(null);
 const notify=(type,text)=>{setMessage({type,text});setTimeout(()=>setMessage(null),3500)};
 const loadOfferings=async()=>{try{const r=await videosApi.getOfferings();setOfferings(r.offerings||[]); if(!selectedOffering&&r.offerings?.[0]) setSelectedOffering(String(r.offerings[0].id));}catch(e){notify('error',e.message)}};
 const loadVideos=async(id=selectedOffering)=>{if(!id){setVideos([]);setLoading(false);return} setLoading(true);try{const r=await videosApi.getVideos({offering_id:id});setVideos(r.videos||[])}catch(e){notify('error',e.message)}finally{setLoading(false)}};
 useEffect(()=>{loadOfferings()},[]); useEffect(()=>{loadVideos()},[selectedOffering]);
 const offering=offerings.find(o=>String(o.id)===String(selectedOffering));
 const visible=useMemo(()=>videos.filter(v=>!search||v.video_title.toLowerCase().includes(search.toLowerCase())),[videos,search]);
 const saveVideo=async payload=>{try{if(videoModal?.mode==='edit') await videosApi.updateVideo(videoModal.video.video_id,payload); else await videosApi.createVideo(payload); setVideoModal(null);await loadVideos();notify('success',videoModal?.mode==='edit'?'Video updated.':'Video added.')}catch(e){notify('error',e.message)}};
 const openEditor=async v=>{try{const r=await videosApi.getEditor(v.video_id);setEditor({...r,questions:(r.questions||[]).map(q=>({dbId:q.question_id,time:q.timestamp_seconds,question:q.question_text,explanation:q.explanation||'',options:(q.question_options||[]).sort((a,b)=>a.option_order-b.option_order).map(x=>x.option_text),correctAnswer:Math.max(0,(q.question_options||[]).sort((a,b)=>a.option_order-b.option_order).findIndex(x=>x.is_correct))})),skips:(r.skips||[]).map(s=>({dbId:s.skip_id,start:s.start_time_seconds,end:s.end_time_seconds}))});setEditorTab('questions')}catch(e){notify('error',e.message)}};
 const saveEditor=async()=>{try{await videosApi.saveEditor(editor.video.video_id,{...editor.video,questions:editor.questions,skips:editor.skips});setEditor(null);await loadVideos();notify('success','Video editor saved.')}catch(e){notify('error',e.message)}};
 const deleteVideo=async v=>{if(!confirm(`Delete "${v.video_title}"? All questions and skips will also be removed.`))return;try{await videosApi.deleteVideo(v.video_id);await loadVideos();notify('success','Video deleted.')}catch(e){notify('error',e.message)}};
 const move=async(v,d)=>{try{await videosApi.moveVideo(v.video_id,d);await loadVideos()}catch(e){notify('error',e.message)}};
 if(editor) return <Editor editor={editor} setEditor={setEditor} tab={editorTab} setTab={setEditorTab} qModal={qModal} setQModal={setQModal} onSave={saveEditor} />;
 return <section className="space-y-6">
  {message&&<div className={`rounded-xl border px-4 py-3 text-sm ${message.type==='error'?'border-red-200 bg-red-50 text-red-700':'border-emerald-200 bg-emerald-50 text-emerald-700'}`}>{message.text}</div>}
  <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-2xl font-bold text-slate-900">Videos</h2><p className="mt-1 text-sm text-slate-500">Manage YouTube lessons, questions, skip sections and student playback settings.</p></div><div className="flex flex-wrap gap-2"><button onClick={()=>navigate(`/admin/courses${offering?.folder_id ? `?folder_id=${offering.folder_id}` : ''}`)} className="inline-flex items-center gap-2 rounded-lg border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold text-slate-700 hover:bg-slate-50"><ArrowLeft size={17}/> Back to Courses</button><button onClick={()=>setVideoModal({mode:'add',video:{offering_id:selectedOffering}})} className="inline-flex items-center gap-2 rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white"><Plus size={17}/> Add Video</button></div></div>
  <div className="grid gap-3 md:grid-cols-[minmax(260px,1fr)_260px_auto]"><div className="relative"><Search size={17} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search videos..." className="w-full rounded-xl border border-slate-200 bg-white py-3 pl-9 pr-3 text-sm outline-none focus:border-blue-400"/></div><select value={selectedOffering} onChange={e=>setSelectedOffering(e.target.value)} className="rounded-xl border border-slate-200 bg-white px-3 text-sm"><option value="">Select course offering</option>{offerings.map(o=><option key={o.id} value={o.id}>{o.courses?.course_name||`Course ${o.id}`}</option>)}</select><button onClick={()=>loadVideos()} className="rounded-xl border border-slate-200 bg-white px-4 py-2 text-sm font-semibold text-slate-600">Refresh</button></div>
  {offering&&<div className="rounded-2xl border border-blue-100 bg-blue-50 p-4"><div className="flex items-center gap-2 text-sm font-semibold text-blue-900"><ChevronRight size={16}/> {offering.courses?.course_name||'Course'} <span className="font-normal text-blue-700">· {offering.is_published?'Published':'Draft'}</span></div></div>}
  {loading?<div className="flex min-h-[30vh] items-center justify-center text-slate-500"><Loader2 className="mr-2 animate-spin"/>Loading videos...</div>:!selectedOffering?<div className="rounded-2xl border border-dashed border-slate-300 p-12 text-center text-slate-500">Select a course offering to manage its videos.</div>:visible.length===0?<div className="rounded-2xl border border-dashed border-slate-300 p-12 text-center text-slate-500">No videos found.</div>:<div className="space-y-3">{visible.map((v,i)=><div key={v.video_id} className="flex flex-col gap-4 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm lg:flex-row lg:items-center"><div className="h-28 w-full overflow-hidden rounded-xl bg-slate-100 lg:w-52">{ytId(v.youtube_url)?<img className="h-full w-full object-cover" src={`https://img.youtube.com/vi/${ytId(v.youtube_url)}/hqdefault.jpg`} alt=""/>:<div className="grid h-full place-items-center text-sm text-slate-400">Invalid YouTube URL</div>}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-slate-100 px-2 py-1 text-[11px] font-bold text-slate-600">#{v.display_order||i+1}</span><h3 className="font-bold text-slate-900">{v.video_title}</h3></div><p className="mt-1 line-clamp-2 text-sm text-slate-500">{v.description||'No description'}</p><div className="mt-3 flex flex-wrap gap-2 text-xs text-slate-500"><span>{v.pause_at_questions?'Pauses at questions':'Questions do not pause'}</span><span>·</span><span>Max {Number(v.playback_speed||1)}×</span>{v.start_date&&<><span>·</span><span>Starts {v.start_date}</span></>}{v.end_date&&<><span>·</span><span>Ends {v.end_date}</span></>}</div></div><div className="flex flex-wrap items-center gap-2"><button title="Move up" onClick={()=>move(v,'up')} className="rounded-lg border p-2 text-slate-500"><ArrowUp size={16}/></button><button title="Move down" onClick={()=>move(v,'down')} className="rounded-lg border p-2 text-slate-500"><ArrowDown size={16}/></button><button onClick={()=>openEditor(v)} className="inline-flex items-center gap-2 rounded-lg bg-blue-600 px-3 py-2 text-sm font-semibold text-white"><Edit3 size={15}/> Editor</button><button onClick={()=>setVideoModal({mode:'edit',video:v})} className="rounded-lg border px-3 py-2 text-sm font-semibold text-slate-600">Edit</button><button onClick={()=>deleteVideo(v)} className="rounded-lg border border-red-200 px-3 py-2 text-sm font-semibold text-red-600"><Trash2 size={15}/></button></div></div>)}</div>}
  {videoModal&&<VideoModal modal={videoModal} offerings={offerings} onClose={()=>setVideoModal(null)} onSave={saveVideo}/>} 
 </section>;
}

function VideoModal({modal,offerings,onClose,onSave}){const v=modal.video||{};const [f,setF]=useState({offering_id:v.offering_id||'',video_title:v.video_title||'',youtube_url:v.youtube_url||'',description:v.description||''});return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-900/50 p-4"><div className="w-full max-w-xl rounded-2xl bg-white shadow-xl"><div className="flex items-center justify-between border-b p-5"><h3 className="text-lg font-bold">{modal.mode==='edit'?'Edit Video':'Add Video'}</h3><button onClick={onClose}><X/></button></div><div className="space-y-4 p-5"><label className="block text-sm font-semibold">Course<select value={f.offering_id} disabled={modal.mode==='edit'} onChange={e=>setF({...f,offering_id:e.target.value})} className="mt-1 w-full rounded-lg border px-3 py-2 font-normal"><option value="">Select offering</option>{offerings.map(o=><option key={o.id} value={o.id}>{o.courses?.course_name||`Course ${o.id}`}</option>)}</select></label><label className="block text-sm font-semibold">Video title<input value={f.video_title} onChange={e=>setF({...f,video_title:e.target.value})} className="mt-1 w-full rounded-lg border px-3 py-2 font-normal"/></label><label className="block text-sm font-semibold">YouTube URL<input value={f.youtube_url} onChange={e=>setF({...f,youtube_url:e.target.value})} placeholder="https://youtu.be/..." className="mt-1 w-full rounded-lg border px-3 py-2 font-normal"/></label><label className="block text-sm font-semibold">Description<textarea value={f.description} onChange={e=>setF({...f,description:e.target.value})} rows="3" className="mt-1 w-full rounded-lg border px-3 py-2 font-normal"/></label></div><div className="flex justify-end gap-2 border-t p-5"><button onClick={onClose} className="rounded-lg border px-4 py-2 text-sm font-semibold">Cancel</button><button onClick={()=>onSave(f)} className="rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white">Save</button></div></div></div>}

function Editor({editor,setEditor,tab,setTab,qModal,setQModal,onSave}){
 const v=editor.video; const id=ytId(v.youtube_url);
 const [time,setTime]=useState(0); const [duration,setDuration]=useState(0);
 const [preview,setPreview]=useState(false);
 const [previewQuestion,setPreviewQuestion]=useState(null);
 const [answered,setAnswered]=useState(new Set());
 const [maxReached,setMaxReached]=useState(0);
 const [skipping,setSkipping]=useState(false);
 const [skipStart,setSkipStart]=useState(null);
 const [skipEnd,setSkipEnd]=useState(null);
 const playerRef=useRef(null);
 const addQ=()=>setQModal({mode:'add',q:{...emptyQ(),time:Math.round(time)}});
 const seek=t=>{ if(playerRef.current) playerRef.current.seekTo(t); };
 const enterPreview=()=>{setPreview(true);setPreviewQuestion(null);setAnswered(new Set());setMaxReached(0);setSkipping(false);setTime(0);};
 const exitPreview=()=>{setPreview(false);setPreviewQuestion(null);setSkipping(false);};
 const handlePreviewTime=(now)=>{
   setTime(now);
   if(!preview || previewQuestion || skipping) return;
   const block=v.block_forward_seek!==false;
   if(block && now>maxReached+1.25){ playerRef.current?.seekTo(maxReached); return; }
   if(block) setMaxReached(m=>Math.max(m,now)); else setMaxReached(m=>Math.max(m,now));
   const skip=editor.skips.find(s=>now>=Number(s.start) && now<Number(s.end));
   if(skip){ setSkipping(true); setMaxReached(m=>Math.max(m,Number(skip.end))); playerRef.current?.seekTo(Number(skip.end)); setTimeout(()=>setSkipping(false),700); return; }
   const q=editor.questions.find(q=>!answered.has(q.dbId||q._previewIndex) && Math.abs(now-Number(q.time))<0.8);
   if(q){
     const key=q.dbId||q._previewIndex||editor.questions.indexOf(q); setPreviewQuestion({...q,_previewKey:key});
     if(v.pause_at_questions!==false) playerRef.current?.pause();
   }
 };
 const submitPreviewAnswer=(idx)=>{
   if(!previewQuestion) return;
   if(idx===previewQuestion.correctAnswer){
     const key=previewQuestion._previewKey;
     setAnswered(prev=>{const n=new Set(prev);n.add(key);return n;});
     setPreviewQuestion({...previewQuestion,_feedback:'correct'});
     setTimeout(()=>{setPreviewQuestion(null);playerRef.current?.play();},1000);
   } else setPreviewQuestion({...previewQuestion,_feedback:'wrong'});
 };
 const startSkip=()=>{setSkipStart(Math.round(time));setSkipEnd(null);};
 const finishSkip=()=>{const e=Math.round(time);if(skipStart===null||e<=skipStart){return;}setEditor(x=>({...x,skips:[...x.skips,{start:skipStart,end:e}]}));setSkipStart(null);setSkipEnd(null);setSkipEnd(e);};
 return <section className="space-y-5">
  <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
   <div><button onClick={()=>setEditor(null)} className="mb-2 inline-flex items-center gap-1 text-sm font-semibold text-blue-600"><ArrowLeft size={16}/> Back to Videos</button><h2 className="text-2xl font-bold text-slate-900">{v.video_title}</h2><p className="text-sm text-slate-500">{preview?'Student Preview — test the video exactly as a student will experience it.':'Interactive video editor'}</p></div>
   <div className="flex flex-wrap gap-2">
    {preview?<button onClick={exitPreview} className="inline-flex items-center gap-2 rounded-lg border border-blue-200 bg-blue-50 px-4 py-2.5 text-sm font-semibold text-blue-700"><Edit3 size={16}/> Back to Editor</button>:<><button onClick={enterPreview} className="inline-flex items-center gap-2 rounded-lg border border-blue-200 bg-blue-50 px-4 py-2.5 text-sm font-semibold text-blue-700"><Eye size={16}/> Student Preview</button><button onClick={onSave} className="inline-flex items-center gap-2 rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white"><Save size={16}/> Save to Database</button></>}
   </div>
  </div>
  {preview ? <PreviewPanel editor={editor} id={id} time={time} duration={duration} playerRef={playerRef} onReadyDuration={setDuration} onTime={handlePreviewTime} question={previewQuestion} onAnswer={submitPreviewAnswer} onRewatch={()=>{if(!previewQuestion)return;const target=Math.max(0,Number(time)-15);setPreviewQuestion(null);setSkipping(false);playerRef.current?.seekTo(target);playerRef.current?.play();setTime(target);}} onExit={exitPreview}/>
  : <>
   <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_380px]"><div className="rounded-2xl border bg-white p-4 shadow-sm"><YouTubePlayer id={id} playerRef={playerRef} onTime={setTime} onDuration={setDuration} maxSpeed={null}/><div className="mt-4 flex items-center justify-between text-sm text-slate-500"><span>{fmt(time)} / {fmt(duration)}</span><span>{editor.questions.length} questions · {editor.skips.length} skips</span></div><div className="mt-3 flex flex-wrap gap-2"><button onClick={addQ} className="inline-flex items-center gap-2 rounded-lg bg-blue-600 px-3 py-2 text-sm font-semibold text-white"><Plus size={15}/> Add Question at {fmt(time)}</button><button onClick={()=>{if(skipStart===null) startSkip(); else finishSkip();}} className={`inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-sm font-semibold ${skipStart!==null?'border-amber-300 bg-amber-50 text-amber-700':'text-slate-700'}`}><SkipForward size={15}/>{skipStart===null?'Set Skip Start Here':'Set Skip End Here'}</button>{skipStart!==null&&<button onClick={()=>{setSkipStart(null);setSkipEnd(null)}} className="rounded-lg border px-3 py-2 text-sm font-semibold text-slate-500">Cancel Skip</button>}</div>{skipStart!==null&&<p className="mt-2 text-xs text-amber-700">Skip start: {fmt(skipStart)}. Move the video to the end point and click <b>Set Skip End Here</b>.</p>}</div>
    <div className="rounded-2xl border bg-white shadow-sm"><div className="grid grid-cols-2 border-b"><button onClick={()=>setTab('questions')} className={`p-3 text-sm font-semibold ${tab==='questions'?'border-b-2 border-blue-600 text-blue-600':'text-slate-500'}`}>Questions ({editor.questions.length})</button><button onClick={()=>setTab('skips')} className={`p-3 text-sm font-semibold ${tab==='skips'?'border-b-2 border-blue-600 text-blue-600':'text-slate-500'}`}>Skips ({editor.skips.length})</button></div><div className="max-h-[620px] space-y-3 overflow-auto p-4">{tab==='questions'?<>{editor.questions.map((q,i)=><div key={i} className="rounded-xl border p-3"><div className="flex justify-between gap-2"><button onClick={()=>seek(q.time)} className="text-left"><span className="rounded bg-blue-50 px-2 py-1 text-xs font-bold text-blue-700">{fmt(q.time)}</span><p className="mt-2 text-sm font-semibold text-slate-800">{q.question||'Untitled question'}</p></button><button onClick={()=>setQModal({mode:'edit',index:i,q:{...q,options:[...q.options]}})} className="text-slate-500"><Edit3 size={15}/></button></div><p className="mt-2 text-xs text-slate-500">Correct: {q.options[q.correctAnswer]||'—'}</p></div>)}<button onClick={addQ} className="flex w-full items-center justify-center gap-2 rounded-lg border border-dashed p-3 text-sm font-semibold text-blue-600"><Plus size={16}/> Add Question</button></>:<><div className="rounded-xl border border-dashed p-3 text-xs text-slate-500">Set a start and end from the current video position. Students are automatically advanced over saved skip ranges.</div>{editor.skips.map((s,i)=><div key={i} className="flex items-center justify-between rounded-xl border p-3"><button onClick={()=>seek(s.start)} className="text-sm font-semibold">{fmt(s.start)} → {fmt(s.end)}</button><button onClick={()=>setEditor(e=>({...e,skips:e.skips.filter((_,j)=>j!==i)}))} className="text-red-500"><Trash2 size={15}/></button></div>)}<button onClick={startSkip} className="flex w-full items-center justify-center gap-2 rounded-lg border border-dashed p-3 text-sm font-semibold text-blue-600"><SkipForward size={16}/> Start Skip at Current Time</button></>}</div></div></div>
   <div className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-center gap-2 font-bold"><Settings2 size={18}/> Student Preview Settings</div><div className="mt-4 grid gap-4 md:grid-cols-2"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={v.block_forward_seek!==false} onChange={e=>setEditor(x=>({...x,video:{...x.video,block_forward_seek:e.target.checked}}))}/> Block forward seeking</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={v.pause_at_questions!==false} onChange={e=>setEditor(x=>({...x,video:{...x.video,pause_at_questions:e.target.checked}}))}/> Pause at questions</label><label className="text-sm font-semibold">Maximum playback speed<select value={v.playback_speed||1} onChange={e=>setEditor(x=>({...x,video:{...x.video,playback_speed:Number(e.target.value)}}))} className="ml-2 rounded-lg border px-2 py-1 font-normal">{[1,1.25,1.5,1.75,2].map(n=><option key={n}>{n}</option>)}</select></label><label className="text-sm font-semibold">Start date<input type="date" value={v.start_date||''} onChange={e=>setEditor(x=>({...x,video:{...x.video,start_date:e.target.value||null}}))} className="ml-2 rounded-lg border px-2 py-1 font-normal"/></label><label className="text-sm font-semibold">End date<input type="date" value={v.end_date||''} onChange={e=>setEditor(x=>({...x,video:{...x.video,end_date:e.target.value||null}}))} className="ml-2 rounded-lg border px-2 py-1 font-normal"/></label></div></div>
  </>}
  {qModal&&<QuestionModal modal={qModal} onClose={()=>setQModal(null)} onSave={q=>{setEditor(e=>({...e,questions:qModal.mode==='edit'?e.questions.map((x,i)=>i===qModal.index?q:x):[...e.questions,q]}));setQModal(null)}}/>}
 </section>
}

function YouTubePlayer({id,playerRef,onTime,onDuration,maxSpeed}){
 const hostRef=useRef(null); const localRef=useRef(null); const callbacks=useRef({onTime,onDuration,maxSpeed});
 callbacks.current={onTime,onDuration,maxSpeed};
 useEffect(()=>{
  let mounted=true;
  const init=()=>{
   if(!mounted||!id||!window.YT?.Player||!hostRef.current)return;
   if(localRef.current){try{localRef.current.destroy()}catch{} localRef.current=null;}
   localRef.current=new window.YT.Player(hostRef.current,{videoId:id,playerVars:{enablejsapi:1,rel:0},events:{onReady:e=>{
    if(!mounted)return;
    playerRef.current={play:()=>e.target.playVideo(),pause:()=>e.target.pauseVideo(),seekTo:t=>e.target.seekTo(Number(t),true),getTime:()=>e.target.getCurrentTime(),setPlaybackRate:r=>e.target.setPlaybackRate(Number(r)),getPlaybackRate:()=>e.target.getPlaybackRate()};
    callbacks.current.onDuration?.(e.target.getDuration());
    const max=callbacks.current.maxSpeed;
    if(max)e.target.setPlaybackRate(Math.min(Number(max),2));
   }}});
  };
  if(window.YT?.Player) init();
  else {
   const existing=document.querySelector('script[src="https://www.youtube.com/iframe_api"]');
   if(!existing){const script=document.createElement('script');script.src='https://www.youtube.com/iframe_api';document.head.appendChild(script);}
   const old=window.onYouTubeIframeAPIReady;
   window.onYouTubeIframeAPIReady=()=>{old?.();init();};
  }
  const timer=setInterval(()=>{
   if(!localRef.current?.getCurrentTime)return;
   callbacks.current.onTime?.(localRef.current.getCurrentTime());
   if(localRef.current.getDuration)callbacks.current.onDuration?.(localRef.current.getDuration());
   const max=callbacks.current.maxSpeed;
   if(max&&localRef.current.getPlaybackRate&&localRef.current.getPlaybackRate()>Number(max))localRef.current.setPlaybackRate(Number(max));
  },250);
  return()=>{mounted=false;clearInterval(timer);if(localRef.current){try{localRef.current.destroy()}catch{}localRef.current=null;}if(playerRef.current)playerRef.current=null;};
 },[id]);
 return <div className="aspect-video overflow-hidden rounded-xl bg-black"><div ref={hostRef} className="h-full w-full"/></div>;
}

function PreviewPanel({editor,id,time,duration,playerRef,onReadyDuration,onTime,question,onAnswer,onRewatch,onExit}){
 return <div className="rounded-2xl border bg-white p-4 shadow-sm"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><span className="rounded-full bg-blue-100 px-3 py-1 text-xs font-bold text-blue-700">STUDENT PREVIEW</span><p className="mt-2 text-sm text-slate-500">Testing unsaved editor settings, questions and skips.</p></div><div className="text-sm font-semibold text-slate-600">{fmt(time)} / {fmt(duration)}</div></div><div className="relative"><YouTubePlayer id={id} playerRef={playerRef} onTime={onTime} onDuration={onReadyDuration} maxSpeed={editor.video.playback_speed||1}/>{question&&<PreviewQuestion question={question} onAnswer={onAnswer} onRewatch={onRewatch}/>}</div><div className="mt-4 grid gap-3 md:grid-cols-3"><div className="rounded-xl bg-slate-50 p-3 text-sm"><b>Forward seeking:</b> {editor.video.block_forward_seek!==false?'Blocked':'Allowed'}</div><div className="rounded-xl bg-slate-50 p-3 text-sm"><b>Question pause:</b> {editor.video.pause_at_questions!==false?'Enabled':'Disabled'}</div><div className="rounded-xl bg-slate-50 p-3 text-sm"><b>Max speed:</b> {Number(editor.video.playback_speed||1)}×</div></div><button onClick={onExit} className="mt-4 inline-flex items-center gap-2 rounded-lg border px-4 py-2 text-sm font-semibold text-slate-700"><Edit3 size={15}/> Return to Editor</button></div>
}

function PreviewQuestion({question,onAnswer,onRewatch}){
 const [selected,setSelected]=useState(null); const letters=['A','B','C','D'];
 return <div className="absolute inset-0 z-10 flex items-center justify-center bg-slate-950/75 p-4"><div className="w-full max-w-xl rounded-2xl bg-white p-6 shadow-2xl"><div className="text-xs font-bold uppercase tracking-wide text-blue-600">Question at {fmt(question.time)}</div><h3 className="mt-2 text-lg font-bold text-slate-900">{question.question}</h3><div className="mt-4 space-y-2">{question.options.map((opt,i)=><button key={i} disabled={question._feedback==='correct'} onClick={()=>setSelected(i)} className={`flex w-full items-center gap-3 rounded-xl border p-3 text-left text-sm ${selected===i?'border-blue-500 bg-blue-50':'border-slate-200'} ${question._feedback==='correct'&&i===question.correctAnswer?'border-emerald-500 bg-emerald-50':''}`}><span className="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-slate-100 font-bold">{letters[i]}</span>{opt||`Option ${i+1}`}</button>)}</div>{question._feedback==='wrong'&&<p className="mt-3 text-sm font-semibold text-red-600">Incorrect — try again.</p>}{question._feedback==='correct'&&<p className="mt-3 text-sm font-semibold text-emerald-600">Correct! {question.explanation||'Well done!'}</p>}<div className="mt-5 flex flex-wrap items-center justify-between gap-2"><button type="button" onClick={onRewatch} className="inline-flex items-center gap-2 rounded-lg border border-slate-300 px-4 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-50">↶ Rewatch 15s</button><button disabled={selected===null||question._feedback==='correct'} onClick={()=>onAnswer(selected)} className="rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">Submit Answer</button></div></div></div>
}

function QuestionModal({modal,onClose,onSave}){const [q,setQ]=useState(modal.q);const setOpt=(i,val)=>setQ({...q,options:q.options.map((x,j)=>j===i?val:x)});return <div className="fixed inset-0 z-[60] grid place-items-center bg-slate-900/50 p-4"><div className="w-full max-w-2xl rounded-2xl bg-white shadow-xl"><div className="flex items-center justify-between border-b p-5"><h3 className="font-bold">{modal.mode==='edit'?'Edit Question':'Add Question'}</h3><button onClick={onClose}><X/></button></div><div className="space-y-4 p-5"><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Timestamp (seconds)<input type="number" min="0" value={q.time} onChange={e=>setQ({...q,time:Number(e.target.value)})} className="mt-1 w-full rounded-lg border px-3 py-2 font-normal"/></label><label className="text-sm font-semibold">Correct option<select value={q.correctAnswer} onChange={e=>setQ({...q,correctAnswer:Number(e.target.value)})} className="mt-1 w-full rounded-lg border px-3 py-2 font-normal">{q.options.map((_,i)=><option key={i} value={i}>Option {i+1}</option>)}</select></label></div><label className="block text-sm font-semibold">Question<textarea rows="3" value={q.question} onChange={e=>setQ({...q,question:e.target.value})} className="mt-1 w-full rounded-lg border px-3 py-2 font-normal"/></label>{q.options.map((x,i)=><input key={i} value={x} onChange={e=>setOpt(i,e.target.value)} placeholder={`Option ${i+1}`} className="w-full rounded-lg border px-3 py-2 text-sm"/>)}<label className="block text-sm font-semibold">Explanation<textarea rows="2" value={q.explanation} onChange={e=>setQ({...q,explanation:e.target.value})} className="mt-1 w-full rounded-lg border px-3 py-2 font-normal"/></label></div><div className="flex justify-end gap-2 border-t p-5"><button onClick={onClose} className="rounded-lg border px-4 py-2 text-sm font-semibold">Cancel</button><button onClick={()=>onSave(q)} className="rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white">Save Question</button></div></div></div>}
